apiVersion: v1 
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
  namespace: default
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres